// Copyright Sierra
// This file is auto-generated by generate-registry.ts
// Do not edit this file directly

import { makeRegistry } from "@sierra/agent";
import catFactsApi from "./cat-facts-api";
import pokemonApi from "./pokemon-api";
import sierraOutfitters from "./sierra-outfitters";

const modules = {
  "sierra-university-reference-agent/cat-facts-api": catFactsApi,
  "sierra-university-reference-agent/pokemon-api": pokemonApi,
  "sierra-university-reference-agent/sierra-outfitters": sierraOutfitters,
};

export default makeRegistry(modules);
