// Copyright Sierra
// This file is auto-generated by the Sierra SDK. DO NOT EDIT.

import { useCMSwithContent, type Locale } from "@sierra/agent";

export type CoreVoiceConfig = {
  persona: string;
  speakingRate?: number;
  keywords: string[];
  webDisclosure?: string;
  enableOutboundDtmfBot?: boolean;
  inactivityTimeoutSeconds?: number;
  inactivityMaxCount?: number;
  inactivityPromptMessage?: string;
  inactivityHangupMessage?: string;
  inactivityMode?: "static" | "adaptive";
  adaptiveMinWaitSeconds?: number;
  adaptiveMaxWaitSeconds?: number;
  localeConfigs: {
    locale: string;
    persona?: string;
    speakingRate?: number;
    keywords: string[];
    greeting?: string;
    uninterruptibleGreeting: boolean;
    synthesisRewrites: {
      pattern: string;
      replacement: string;
    }[];
    inactivityPromptMessage?: string;
    inactivityHangupMessage?: string;
  }[];
};

export type CoreAgentConfig = {
  progressIndicators?: {
    mode: "personalized" | "none";
    initialDelayMs?: number;
    trailingSilenceMs?: number;
    chatEnabled: boolean;
    additionalInstructions?: string;
  };
  disabledDefaults?: (
    | "conservative-transfer"
    | "detect-deadlocks"
    | "standard-prompts"
    | "detect-missing-policy"
    | "voice-attachments"
    | "reasoning-progress-indicator"
    | "low-confidence-transcription"
  )[];
  learningModes?: (
    | "observation"
    | "respond"
    | "hallucination"
    | "parameter"
    | "check-bounds:silent"
    | "check-bounds:pre-check"
    | "check-bounds:post-check"
  )[];
};

export type PersonaConfig = {
  personalityTraits?: (
    | "standard-customer-service"
    | "behavior-curious"
    | "behavior-conclusive"
    | "behavior-focused"
    | "voice-standard"
    | "voice-modality-context"
    | "voice-long-identifiers"
    | "email-modality-context"
    | "style-professional"
    | "style-conversational"
    | "style-colloquial"
    | "style-informal"
    | "style-concise"
    | "style-thorough"
    | "style-active-voice"
    | "delivery-crisp"
    | "delivery-measured"
    | "delivery-expressive"
    | "delivery-free"
    | "tone-tactful"
    | "tone-empathetic"
    | "tone-warm"
    | "tone-confident"
    | "tone-energetic"
  )[];
};

export type CoreAgentPersonaConfig = {
  personalityTraits: {
    [key: string]: {
      value?: (
        | "standard-customer-service"
        | "behavior-curious"
        | "behavior-conclusive"
        | "behavior-focused"
        | "voice-standard"
        | "voice-modality-context"
        | "voice-long-identifiers"
        | "email-modality-context"
        | "style-professional"
        | "style-conversational"
        | "style-colloquial"
        | "style-informal"
        | "style-concise"
        | "style-thorough"
        | "style-active-voice"
        | "delivery-crisp"
        | "delivery-measured"
        | "delivery-expressive"
        | "delivery-free"
        | "tone-tactful"
        | "tone-empathetic"
        | "tone-warm"
        | "tone-confident"
        | "tone-energetic"
        | "base-channel-optimization"
        | "style-british-wording"
        | "style-german-wording"
        | "style-australian-wording"
        | "style-irish-wording"
        | "style-quebec-register"
        | "style-swedish-wording"
        | "taglish-code-switching"
      )[];
    };
  };
};

export type DetectAbuseConfig = {
  context?: string;
  globalMode: "defend-terminate" | "defend-transfer";
  globalTerminateMessage?: string;
  globalTransferMessage?: string;
  PersuadePolicies?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  HateHarassmentAbuse?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  SexualContent?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  SelfHarm?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  Illegal?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  ChildEndangerment?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  HighRiskAdvice?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  Violence?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  Jailbreak?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  DiscussPublicEntities?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
  OutOfBounds?: {
    mode?: "defend-terminate" | "defend-transfer";
    terminateMessage?: string;
    transferMessage?: string;
    additionalDescriptions?: string[];
    honeypots?: string[];
    maxAllowed?: number;
    refocusMessage?: string;
  };
};

export type CoreAbuseConfig = {
  config: {
    [key: string]: {
      value: {
        context?: string;
        globalMode: "defend-terminate" | "defend-transfer";
        globalTerminateMessage?: string;
        globalTransferMessage?: string;
        PersuadePolicies?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        HateHarassmentAbuse?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        SexualContent?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        SelfHarm?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        Illegal?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        ChildEndangerment?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        HighRiskAdvice?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        Violence?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        Jailbreak?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        DiscussPublicEntities?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
        OutOfBounds?: {
          mode?: "defend-terminate" | "defend-transfer";
          terminateMessage?: string;
          transferMessage?: string;
          additionalDescriptions?: string[];
          honeypots?: string[];
          maxAllowed?: number;
          refocusMessage?: string;
        };
      };
    };
  };
};

export type CoreAgentResponseSupervision = {
  moderationModes?: (
    | "observation"
    | "respond"
    | "hallucination"
    | "parameter"
    | "check-bounds:silent"
    | "check-bounds:pre-check"
    | "check-bounds:post-check"
  )[];
};

export type CoreProgressIndicators = {
  mode: { [key: string]: { value: "personalized" | "none" } };
  initialDelayMs: { [key: string]: { value?: number } };
  trailingSilenceMs: { [key: string]: { value?: number } };
  chatEnabled: { [key: string]: { value: boolean } };
  additionalInstructions: { [key: string]: { value?: string } };
};

export type CoreReasoningProgressIndicator = {
  disabled: boolean;
};

export type CoreLowConfidenceTranscription = {
  disabled: boolean;
};

export type CoreSuppressVoiceAttachments = {
  disabled: boolean;
};

export type CoreConservativeTransfer = {
  disabled: boolean;
};

export type CoreDetectDeadlocks = {
  disabled: boolean;
};

export type CoreStandardPrompts = {
  disabled: boolean;
};

export type CoreDetectMissingPolicy = {
  disabled: boolean;
};

export type CoreFileUploads = {
  allowedFileUploadTypes?: (
    | "application/pdf"
    | "text/csv"
    | "image/gif"
    | "image/jpeg"
    | "image/jpg"
    | "image/png"
    | "image/webp"
    | "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    | "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    | "application/msword"
    | "application/vnd.ms-excel"
    | "application/vnd.ms-powerpoint"
    | "text/plain"
    | "video/quicktime"
    | "video/mp4"
    | "video/webm"
    | "video/x-msvideo"
  )[];
};

export type CoreAgentErrorMessage = {
  errorMessage: { [key: string]: { value: string } };
};

export type OutboundVoiceGreetingDelay = {
  delayMs?: number;
};

export type CoreAgentVoiceGreeting = {
  defaultGreeting: { [key: string]: { value?: string } };
  uninterruptibleGreeting: { [key: string]: { value: boolean } };
};

export type CoreAgentVoice = {
  persona: { [key: string]: { value: string } };
  speakingRate: { [key: string]: { value?: number } };
};

export type CoreAgentVoiceKeywords = {
  keywords: { [key: string]: { value: string[] } };
};

export type CoreAgentVoiceSynthesisRewrites = {
  enabledDefaultSynthesisRewriteRuleIds: {
    [key: string]: {
      value: {
        id: string;
        label: string;
        description?: string;
        playgroundSample?: string;
      }[];
    };
  };
  synthesisRewrites: {
    [key: string]: {
      value: {
        pattern: string;
        replacement: string;
      }[];
    };
  };
};

export type CoreSafety = {
  description: "By default, agents are not permitted to collect sensitive customer information such as:\n• Social security number\n• Last 4 digits of social security number\n• Passport number\n• Full credit card number\n• Full debit card number\n• CVV\n• Last 4 digits of a payment card number\n• Last 4 digits of credit card number\n• Last 4 digits of debit card number\n• Bank account number\n• ACH routing number\n• Gift card number\n• Last 4 digits of a gift card number\n• Gift card security code\n\nIf your use case requires the agent to collect any of this data, please explicitly enable the relevant categories below.\n\nNote: Full 16-digit card numbers and CVV cannot be collected by the agent directly and must only be collected through other secure methods.\n\nNote: Gift card numbers may or may not fall under PCI scope depending on the provider. If you have confirmed that your customer's gift cards are out of PCI scope, you should disable this category to prevent false positives.";
  allowedSensitiveInfo: (
    | "social security number"
    | "last 4 digits of social security number"
    | "passport number"
    | "bank account number"
    | "ACH routing number"
    | "last 4 digits of a payment card number"
    | "last 4 digits of credit card number"
    | "last 4 digits of debit card number"
    | "gift card number"
    | "last 4 digits of a gift card number"
    | "gift card security code"
  )[];
};

export type CoreBrand = {
  organizationName: { [key: string]: { value: string } };
  agentName: { [key: string]: { value: string } };
  customerServiceTeamName: { [key: string]: { value?: string } };
  customerNoun: { [key: string]: { value?: string } };
};

export type CoreLocaleConfig = {
  defaultLocale: Locale;
  supportedLocales: Locale[];
  allowVoiceLanguageSwitching?: boolean;
  voiceLanguageSwitchDetectionTurnThreshold?: number;
};

export type CoreWebChatVoice = {
  accessMode: "on" | "staging" | "off";
};

export type CoreInactivityHandling = {
  inactivityMode: { [key: string]: { value?: "static" | "adaptive" } };
  inactivityTimeoutSeconds: { [key: string]: { value?: number } };
  inactivityMaxCount: { [key: string]: { value?: number } };
  inactivityPromptMessage: { [key: string]: { value?: string } };
  inactivityHangupMessage: { [key: string]: { value?: string } };
  adaptiveMinWaitSeconds: { [key: string]: { value?: number } };
  adaptiveMaxWaitSeconds: { [key: string]: { value?: number } };
};

export type CorePostConversationConfiguration = {
  postConversationDelaySeconds?: number;
};

export type PackageStructureMigration = {
  migratedPackageContentEntries?: string[];
  fullyMigratedToSdkContent?: boolean;
};

export type Brand = {
  description: "When responding to a request, agent will use these settings.";
  organizationName: string;
  agentName: string;
  customerServiceTeamName?: string;
  customerNoun?: string;
  languageGuidance?: string;
  knowledgeLanguageGuidance?: string;
  glossary?: string;
  rules: string[];
};

export type Voice = {
  voiceGreeting?: string;
  uninterruptibleGreeting: boolean;
  languageGuidance?: string;
  webAccess: "on" | "staging" | "off";
  synthesisRewrites: {
    pattern: string;
    replacement: string;
  }[];
};

export type intentConfiguration = {
  intentName: string;
  intentDescription: string;
  intentTags: string[];
};

export type Errors = {
  description: "Monitor messages in the conversation for common types of abuse and errors.";
  abuseDetectionMode: "defend-terminate" | "defend-transfer" | "observe";
  allowedBehaviors: (
    | "PublicFigure"
    | "NamedIndividual"
    | "OtherCompany"
    | "CustomerOffensive"
    | "OutOfBounds"
  )[];
  abuseDetectedTerminationMessage?: string;
  abuseDetectedTransferMessage?: string;
  errorMessage: string;
  allowedFileUploadTypes: (
    | "application/pdf"
    | "text/csv"
    | "image/gif"
    | "image/jpeg"
    | "image/jpg"
    | "image/png"
    | "image/webp"
    | "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    | "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    | "application/msword"
    | "application/vnd.ms-excel"
    | "application/vnd.ms-powerpoint"
    | "text/plain"
    | "video/quicktime"
    | "video/mp4"
    | "video/webm"
    | "video/x-msvideo"
  )[];
};

export type Safety = {
  description: "By default, agents are not permitted to collect sensitive customer information such as:\n• Social security number\n• Last 4 digits of social security number\n• Passport number\n• Full credit card number\n• Full debit card number\n• CVV\n• Last 4 digits of a payment card number\n• Last 4 digits of credit card number\n• Last 4 digits of debit card number\n• Bank account number\n• ACH routing number\n• Gift card number\n• Last 4 digits of a gift card number\n• Gift card security code\n\nIf your use case requires the agent to collect any of this data, please explicitly enable the relevant categories below.\n\nNote: Full 16-digit card numbers and CVV cannot be collected by the agent directly and must only be collected through other secure methods.\n\nNote: Gift card numbers may or may not fall under PCI scope depending on the provider. If you have confirmed that your customer's gift cards are out of PCI scope, you should disable this category to prevent false positives.";
  allowedSensitiveInfo: (
    | "social security number"
    | "last 4 digits of social security number"
    | "passport number"
    | "bank account number"
    | "ACH routing number"
    | "last 4 digits of a payment card number"
    | "last 4 digits of credit card number"
    | "last 4 digits of debit card number"
    | "gift card number"
    | "last 4 digits of a gift card number"
    | "gift card security code"
  )[];
};

declare const sierra: {
  content: {
    $sdk?: {
      voice?: CoreVoiceConfig;
      agentConfig?: CoreAgentConfig;
      personaConfig?: PersonaConfig;
      agentPersonaConfig?: CoreAgentPersonaConfig;
      detectAbuse?: DetectAbuseConfig;
      abuse?: CoreAbuseConfig;
      agentResponseModeration?: CoreAgentResponseSupervision;
      progressIndicators?: CoreProgressIndicators;
      reasoningProgressIndicator?: CoreReasoningProgressIndicator;
      lowConfidenceTranscription?: CoreLowConfidenceTranscription;
      suppressVoiceAttachments?: CoreSuppressVoiceAttachments;
      conservativeTransfer?: CoreConservativeTransfer;
      detectDeadlocks?: CoreDetectDeadlocks;
      standardPrompts?: CoreStandardPrompts;
      detectMissingPolicy?: CoreDetectMissingPolicy;
      fileUploads?: CoreFileUploads;
      agentErrorMessage?: CoreAgentErrorMessage;
      outboundVoiceGreetingDelayMs?: OutboundVoiceGreetingDelay;
      agentVoiceGreeting?: CoreAgentVoiceGreeting;
      agentVoice?: CoreAgentVoice;
      agentVoiceTranscriptionKeywords?: CoreAgentVoiceKeywords;
      agentVoiceSynthesisRewrites?: CoreAgentVoiceSynthesisRewrites;
      safety?: CoreSafety;
      brand?: CoreBrand;
      localeConfig?: CoreLocaleConfig;
      webChatVoice?: CoreWebChatVoice;
      inactivityHandling?: CoreInactivityHandling;
      postConversationConfiguration?: CorePostConversationConfiguration;
      packageStructureMigration?: PackageStructureMigration;
    };
    brand?: Brand;
    voice?: Voice;
    intents?: intentConfiguration[];
    errors?: Errors;
    safety?: Safety;
  };
};

export const content = sierra.content;
export function useCMS() {
  return useCMSwithContent(sierra.content);
}
