// Copyright Sierra

// This file is auto-generated by running pnpm sierra integrations bundle.

import { makeRegistry } from "@sierra/agent";

import registry0 from "@sierra/integrations-builtin/integrations/registry";
import registry1 from "./integrations/registry";

const modules = {
    ...registry0.modules,
    ...registry1.modules,
};

export default makeRegistry(modules);
