// Copyright Sierra
// This file is auto-generated by generate-bindings.ts
import registry from "./integrations-registry";
import { lazySingletonHook, newChainableToolRegistry } from "@sierra/agent";

export const integrations = {
  get sierraOutfitters() {
    const instance = registry.getInstance(
      "sierra-university-reference-agent/sierra-outfitters",
      "sierraOutfitters",
    )!;
    return instance as IntegrationInstanceWithApi<
      typeof instance,
      SierraUniversityReferenceAgentSierraOutfittersApiClient
    >;
  },
} as const;

export type SierraUniversityReferenceAgentSierraOutfittersApiClient = {
  addToWishlist(args: { customerId: string; productId: string }): {
    added: boolean;
    product_id: string;
    reason: string;
  };
  cancelOrder(args: { orderId: string }): {
    cancelled: boolean;
    order_number: string;
    reason: string;
  };
  createCoupon(args: { customerId: string; reason: string }): {
    [key: string]: any;
  };
  determineReturnEligibility(args: {
    orderId: string;
    returnWindowDays?: number | null;
  }): {
    active_return_id: string;
    days_since_order: number;
    eligible: boolean;
    has_active_return: boolean;
    order_date: string;
    order_status: string;
    reason: string;
    return_window_days: number;
  };
  fetchOrdersForCustomer(args: {
    customerId: string;
    days?: number | null;
    limit?: number | null;
    page?: number | null;
  }): {
    limit: number;
    orders: {
      id: string;
      items: {
        id: string;
        product_name: string;
        quantity: number;
        total_price: number;
        variant_name: string;
      }[];
      order_number: string;
      placed_at: string;
      status: string;
      total: number;
    }[];
    page: number;
    total: number;
    total_pages: number;
  };
  getCategory(args: { description: string }): {
    description: string;
    id: string;
    name: string;
  };
  getCustomerInfo(args: { customerId: string }): {
    addresses: {
      city: string;
      country: string;
      id: string;
      is_default: boolean;
      line1: string;
      state: string;
      type: string;
      zip: string;
    }[];
    created_at: string;
    email: string;
    first_name: string;
    id: string;
    last_name: string;
    phone: string;
    updated_at: string;
  };
  getCustomerWishlist(args: { customerId: string }): {
    items: {
      brand: string;
      category_name: string;
      product_description: string;
      product_id: string;
      product_name: string;
      wishlist_id: string;
    }[];
  };
  getOrderInfo(args: { orderId: string }): {
    billing_address: {
      city: string;
      country: string;
      id: string;
      is_default: boolean;
      line1: string;
      state: string;
      type: string;
      zip: string;
    };
    created_at: string;
    customer_id: string;
    discount: number;
    id: string;
    items: {
      id: string;
      product_id: string;
      product_name: string;
      quantity: number;
      total_price: number;
      unit_price: number;
      variant_id: string;
      variant_name: string;
    }[];
    order_number: string;
    shipments: {
      carrier: string;
      estimated_delivery: string;
      id: string;
      shipped_at: string;
      status: string;
      tracking_number: string;
    }[];
    shipping_address: {
      city: string;
      country: string;
      id: string;
      is_default: boolean;
      line1: string;
      state: string;
      type: string;
      zip: string;
    };
    shipping_cost: number;
    status: string;
    subtotal: number;
    tax: number;
    total: number;
    updated_at: string;
  };
  getShipmentTracking(args: { shipmentId: string }): {
    carrier: string;
    estimated_delivery: string;
    events: {
      description: string;
      location: string;
      status: string;
      timestamp: string;
    }[];
    shipment_id: string;
    status: string;
    tracking_number: string;
  };
  initiateReturn(args: {
    itemReason?: string | null;
    orderId: string;
    orderItemId: string;
    quantity: number;
    reason: string;
  }): {
    created_at: string;
    id: string;
    items: {
      order_item_id: string;
      product_name: string;
      quantity: number;
      reason: string;
      variant_name: string;
    }[];
    order_id: string;
    reason: string;
    refund_amount: number;
    return_label_url: string;
    status: string;
    updated_at: string;
  };
  searchCustomers(args: { email?: string | null; phone?: string | null }): {
    created_at: string;
    email: string;
    first_name: string;
    id: string;
    last_name: string;
    loyalty_tier: string;
    phone: string;
    updated_at: string;
  }[];
};

export type SierraUniversityReferenceAgentSierraOutfittersApi<
  TContext = unknown,
> = {
  init: (
    context: TContext,
  ) => SierraUniversityReferenceAgentSierraOutfittersApiClient;
  useApi: () => SierraUniversityReferenceAgentSierraOutfittersApiClient;
};

type ExtractInstanceApi<TInstance> = TInstance extends { api?: infer TApi }
  ? NonNullable<TApi>
  : never;
type ExtractApiInitContext<TApi> = TApi extends {
  init: (context: infer TContext) => unknown;
}
  ? TContext
  : never;
type IntegrationInstanceWithApi<TInstance, TApiClient> = Omit<
  TInstance,
  "api"
> & {
  api: {
    init: (
      context: ExtractApiInitContext<ExtractInstanceApi<TInstance>>,
    ) => TApiClient;
    useApi: () => TApiClient;
  } & ExtractInstanceApi<TInstance>;
};

type IntegrationsApiByName = {
  readonly sierraOutfitters: SierraUniversityReferenceAgentSierraOutfittersApiClient;
};

/**
 * @deprecated Use the generated `tools` export to register code tools. For direct API access, use
 * `integrations.<handle>.api.useApi()` in SDK render contexts or
 * `integrations.<handle>.api.init(context)` when explicitly providing required contexts.
 */
export const apiContext = {
  apis: lazySingletonHook(() => {
    const apis = {
      sierraOutfitters: integrations.sierraOutfitters.api.useApi(),
    } satisfies IntegrationsApiByName;
    return apis;
  }),
};

export const tools = newChainableToolRegistry(apiContext);
