// This file is auto-generated by the Sierra SDK. DO NOT EDIT.

import {
  jsx,
  type RegisteredToolsTyped,
  NoCodeJourneys,
  type JourneyMetadata,
  type KnowledgeSource,
  type JoinedKnowledgeParams,
} from "@sierra/agent";

declare const sierra: {
  knowledge: {
    join: <S extends KnowledgeSource<any>[]>(
      sources: S,
    ) => KnowledgeSource<JoinedKnowledgeParams<S>>;
    allKnowledgeSources: () => KnowledgeSource[];
    /** Knowledge base: Product Search */
    productSearch: KnowledgeSource;
    /** Knowledge base: Sierra Outfitters Product Support */
    sierraOutfittersProductSupport: KnowledgeSource;
  };
  tools: object;
};

export const knowledge = sierra.knowledge;
export const tools = sierra.tools;
export type JourneyTools = Partial<RegisteredToolsTyped<typeof tools>>;

export const journeys = {};

export function NoCodeJourneysTyped<T extends JourneyTools>({
  tools: registeredTools,
  overrideJourneySetup,
  additionalAgentContext,
  children,
}: {
  tools?: T;
  overrideJourneySetup?: (journeyMetadata: JourneyMetadata) => JourneyMetadata;
  additionalAgentContext?: Parameters<
    typeof NoCodeJourneys
  >[0]["additionalAgentContext"];
  children?: JSX.Element;
}): JSX.Element {
  return (
    <NoCodeJourneys
      tools={registeredTools}
      overrideJourneySetup={overrideJourneySetup}
      additionalAgentContext={additionalAgentContext}
    >
      {children}
    </NoCodeJourneys>
  );
}

// Connected integration APIs (auto-generated)
declare namespace __IntegrationAPIs {
  interface SierraOutfitters {
    [method: string]: (params?: { [key: string]: any }) => any;
  }
}

declare const __integrationApis: {
  sierraOutfitters: __IntegrationAPIs.SierraOutfitters;
};
